# Generated by Django 6.1 on 2026-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ai_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
