# Generated by Django 6.1 on 2026-09-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_ai_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jeremy_mode',
            field=models.CharField(choices=[('serious', 'Seriös'), ('satire', 'Satire')], default='serious', max_length=10),
        ),
    ]
