# Generated by Django 6.1 on 2026-09-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioncategory',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_categories', to='households.household'),
        ),
        migrations.AddConstraint(
            model_name='positioncategory',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_household_category_name'),
        ),
    ]
