# Generated by Django 6.1 on 2026-09-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_positioncategory_household_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncategory',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_categories', to='households.household'),
        ),
    ]
