# Generated by Django 6.1 on 2026-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_alter_positioncategory_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioncategory',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
    ]
