# Generated by Django 6.1 on 2026-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_positioncategory_is_standard'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='positioncategory',
            name='unique_household_category_name',
        ),
        migrations.AddField(
            model_name='positioncategory',
            name='type',
            field=models.CharField(choices=[('income', 'Einkommen'), ('cost', 'Ausgabe')], default='cost', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='positioncategory',
            constraint=models.UniqueConstraint(fields=('household', 'type', 'name'), name='unique_household_category_name_per_type'),
        ),
    ]
