# Generated by Django 6.1 on 2026-09-30 14:13

import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('flag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text='Key für Frontend/Backend, z. B. two_factor', unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=False, help_text='Hauptschalter – aus = für niemanden aktiv')),
                ('rollout_percent', models.PositiveSmallIntegerField(default=0, help_text='Anteil der User (0–100), die das Feature sehen', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, help_text='Diese User sehen das Feature immer (wenn enabled)', related_name='feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
