upstream django_backend {
    server web:8000;
}

server {
    listen 80;
    server_name xn--finanzmnch-kcb.de www.xn--finanzmnch-kcb.de;

    root /usr/share/nginx/html;
    index index.html;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /api/ {
        proxy_pass http://django_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /admin/ {
        proxy_pass http://django_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /account/ {
    proxy_pass http://django_backend
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_redirect off;
    }

    location / {
        try_files $uri /index.html;
    }
}