# Generated by Django 6.1 on 2026-09-20 13:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='person',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='position_category',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='costitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costitem',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.CreateModel(
            name='CostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='finances.costitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='costitem',
            name='shared_by',
            field=models.ManyToManyField(related_name='shared_costs', through='finances.CostShare', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ItemEntry',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddConstraint(
            model_name='costshare',
            constraint=models.UniqueConstraint(fields=('cost_item', 'person'), name='unique_cost_item_person_share'),
        ),
    ]
