# Generated by Django 6.1 on 2026-09-22 05:29

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_transaction_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='history_group_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Gruppiert historische Versionen derselben Ausgabe'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2026, 9, 22, 5, 29, 3, 717420, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costitem',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='history_group_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Gruppiert historische Versionen desselben Einkommens'),
        ),
        migrations.AlterField(
            model_name='income',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
