# Generated by Django 6.1 on 2026-09-26 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_costitem_history_group_id_costitem_valid_from_and_more'),
        ('households', '0002_positioncategory_household_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEntry',
            fields=[
                ('item_entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='costitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='costitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__lt', models.F('start_date')), _negated=True), name='costitem_valid_date_range'),
        ),
        migrations.AddField(
            model_name='itementry',
            name='cost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='finances.costitem'),
        ),
        migrations.AddConstraint(
            model_name='itementry',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__lt', models.F('valid_from')), _negated=True), name='itementry_valid_date_range'),
        ),
    ]
