# Generated by Django 6.1 on 2026-09-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_itementry_costitem_end_date_costitem_start_date_and_more'),
        ('households', '0004_positioncategory_is_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costitem',
            name='position_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.positioncategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='position_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.positioncategory'),
        ),
    ]
