name: test db scheme

on: [push]

jobs:
  test-sql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORT }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: test sql scheme
        run: mysql -h 127.0.0.1 -uroot -p${{ secrets.DB_PASSWORT }} < ./backend/db/schema.sql

      - name: insert test data
        run: mysql -h 127.0.0.1 -uroot -p${{ secrets.DB_PASSWORT }} < ./backend/db/tests/test-db.sql